### ISSUE TITLE
README.md : miss cmake and ninja information

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-tools#149]
### Description

Hi
This morning, I spent some time on a new PC to install this new mbed tool,
This was not working, and I got several not friendly messages...
... till I remembered that I didn't install cmake yet...

So my request would be:
- to update tools when cmake is not installed with some friendly message "please install cmake"
- same for ninja
- to update README.md to add information how to install cmake and ninja

Thx

@0xc0170 
@MarceloSalazar 
@JeanMarcR

### Issue request type

- [x] Enhancement
- [ ] Bug

**Comment by boraozgen** [comment]
Same for git.
