### ISSUE TITLE
Compilation of targets with sector attribute in targets.json fails

### ISSUE THREAD

**Issue by harmut01** [ARMmbed/mbed-tools#182]
### Description
The tool raises the following TypeError when building targets with the sector attribute in `targets.json`: `TypeError: unhashable type: 'list'`. The issues starts with release 4.6.1 where [these changes](https://github.com/ARMmbed/mbed-tools/commit/9935f2fb0b3c1c09f8b94f130f600ccc025da442) were introduced. Observed this building the blinky application for GR_MANGO on MacOS 11.1 with the GCC toolchain.

### Issue request type

- [ ] Enhancement
- [x] Bug

**Comment by Patater** [comment]
This looks like it'll be fixed by https://github.com/ARMmbed/mbed-tools/pull/176
