### ISSUE TITLE
Users are building cli1 and cli2 within the same app

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-tools#233]
**Describe the bug**

I've received 2 questions with the similar topic within the last 24 hours - "my build is failing with a weird error" - a user first run cli2 and then later another day switched to cli1 and received an error.

A question is: should we fix this and avoid surprises if users use either cli1 or cli2 ? One suggestion that many of us came to was adding .mbedignore and add there `cmake_build` directory.  Is there better way to make this use case working without errors ?

**To Reproduce**

Build blinky with cli2 first, then build with cli1.

**Expected behavior**
Both builds would work as they work on the same codebase, in separate build directories. As we support both at the time being, we should allow users to build both or at least warn them if they are doing this (if we do not want to support the use case)

**Mbed (please complete the following information):**
mbed-tools, mbed-cli and Mbed OS - any version

**Comment by LDong-Arm** [comment]
> One suggestion that many of us came to was adding .mbedignore and add there `cmake_build` directory

The reliable way would be let configure and build sub-commands add `cmake_build/.mbedignore` whose content is `*`.
