### ISSUE TITLE
Does not compile with --mbed-os-path option

### ISSUE THREAD

**Issue by boraozgen** [ARMmbed/mbed-tools#234]
**Describe the bug**
As in title.

**To Reproduce**
1. Import an example project.
1. mbed-tools compile -m K64F -t GCC_ARM --mbed-os-path mbed-os

Error:
`ValueError: Setting storage_filesystem.rbp_internal_size already defined. You cannot duplicate config settings!`

The setting name changes every time the command is executed.

**Expected behavior**
Should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Mbed (please complete the following information):**
 - Device: any
 - Mbed OS Version: 6.9.0
 - Mbed CLI 2 Version: 7.8.0

**Additional context**
I assume this has something to do with the dependencies. Here is my pipdeptree output:

```
mbed-tools==7.8.0
  - Click [required: >=7.1,<8, installed: 7.1]
  - GitPython [required: Any, installed: 3.1.14]
    - gitdb [required: >=4.0.1,<5, installed: 4.0.5]
      - smmap [required: >=3.0.1,<4, installed: 3.0.5]
  - Jinja2 [required: Any, installed: 2.11.3]
    - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - pdoc3 [required: Any, installed: 0.9.2]
    - mako [required: Any, installed: 1.1.4]
      - MarkupSafe [required: >=0.9.2, installed: 1.1.1]
    - markdown [required: >=3.0, installed: 3.3.4]
  - pyserial [required: Any, installed: 3.5]
  - python-dotenv [required: Any, installed: 0.15.0]
  - pywin32 [required: Any, installed: 300]
  - requests [required: >=2.20, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2020.12.5]
    - chardet [required: >=3.0.2,<5, installed: 4.0.0]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
  - tabulate [required: Any, installed: 0.8.9]
  - tqdm [required: Any, installed: 4.59.0]
  - typing-extensions [required: Any, installed: 3.7.4.3]
```

**Comment by boraozgen** [comment]
Seems to be a problem with my python dependencies. Seems to be working now. Closing.

**Comment by boraozgen** [comment]
This keeps happening for me. Reopening.

**Comment by Patater** [comment]
@boraozgen What did you find the issue with your Python dependencies was?

**Comment by boraozgen** [comment]
Well I am not that experienced with python&pip so I removed and reinstalled some stuff and it started working. Now it seems broken again. I cannot point to the change which broke/fixed it. I updated the issue description with my current dependency tree.

**Comment by Patater** [comment]
I can confirm I am able to reproduce this. Looks we are searching the same settings twice. We'll have to avoid this.

**Comment by Patater** [comment]
I'm also able to reproduce with `mbed-tools compile -m K64F -t GCC_ARM --mbed-os-path extern/mbed-os`. Probably any path to mbed-os within the application directory would hit this issue.

**Comment by ladislas** [comment]
I'm also hitting the same issue! :)
