### ISSUE TITLE
Target detection not working for ARM_MUSCA_B1

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-tools#272]
**Describe the bug**
`mbed-tools detect` is not working for ARM_MUSCA_B1. Same with the `-f` option of `mbed-tools compile`, so it's a target detection issue.

**To Reproduce**
1. Connect an ARM_MUSCA_B1 board to PC and wait for it to enumerate
2. Run `mbed-tools detect`. The error is
```
ERROR: Could not identify a board with the product code: '5007'.
No connected Mbed devices found.
```

**Expected behavior**
The target ARM_MUSCA_B1 should be recognised. Output from the old tools (`mbed detect`):
```
[mbed] Detected ARM_MUSCA_B1, port /dev/tty.usbmodem143102, mounted /Volumes/MUSCA_B, interface version 0242:
[mbed] Supported toolchains for ARM_MUSCA_B1
| Target       | mbed OS 2 | mbed OS 5 |    ARM    | uARM |  GCC_ARM  | IAR |
|--------------|-----------|-----------|-----------|------|-----------|-----|
| ARM_MUSCA_B1 |     -     | Supported | Supported |  -   | Supported |  -  |
Supported targets: 1
Supported toolchains: 2
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.2.3 (Big Sur)

**Mbed (please complete the following information):**
 - Device: ARM_MUSCA_B1
 - Mbed OS Version: 6.9.0
 - Mbed CLI 2 Version: 7.10.0

**Additional context**

**Comment by LDong-Arm** [comment]
ARM_MUSCA_B1 boards are relatively rare and I have one, so I assigned this issue to myself. It's not critical so I may not fix it right away.

**Comment by Patater** [comment]
Could this be because `targets/targets.json` for the B1 doesn't have a `"detect_code"` entry? S1 has it as `5009`. I don't see an entry for B1.

**Comment by Patater** [comment]
Looks my proposed fix to add `detect_code` to `targets.json` isn't going to work if the tools don't look at the `detect_code`.

**Comment by LDong-Arm** [comment]
> Looks my proposed fix to add `detect_code` to `targets.json` isn't going to work if the tools don't look at the `detect_code`.

Thanks for the PR, it's needed anyway.

**Comment by rwalton-arm** [comment]
We probably need to update the online database. Looks like we only have an entry for MUSCA_S1.
