### ISSUE TITLE
docs: Creating a new project

### ISSUE THREAD

**Issue by urutva** [ARMmbed/mbed-tools#65]
### Description

There are two ways to create a new project as described in https://github.com/ARMmbed/mbed-tools/blob/master/docs/howto/mbed-tools-howto.md#create-a-project. But it is not very clear on how to use the `-c (create-only) option. We should add detailed description on how to create sym-links to existing mbed-os.

### Issue request type

- [ ] Enhancement
- [ ] Bug

**Comment by jainvikas8** [comment]
This is already been addressed in https://github.com/ARMmbed/mbed-tools/blob/master/docs/howto/mbed-tools-howto.md#create-a-new-project
