### ISSUE TITLE
mbedtools clone <example> fails

### ISSUE THREAD

**Issue by urutva** [ARMmbed/mbed-tools#66]
### Description

The clone command `mbedtools clone https://github.com/ARMmbed/mbed-os-example-blinky` fails with following error:
```
Cloning Mbed program 'https://github.com/ARMmbed/mbed-os-example-blinky'
Resolving program library dependencies.
ERROR: Cloning git repository from url 'https://github.com/ARMmbed/mbed-os/' failed. Error from VCS:

More information may be available by using the command line option '-v'.
```

### Issue request type

- [ ] Enhancement
- [x] Bug

**Comment by jainvikas8** [comment]
This bug is reproducible when `git config --global` on the host machine has ssh redirection

One way to reproduce is to have
`git config --global url.ssh://git@github.com/.insteadOf https://github.com/`
