### ISSUE TITLE
docs: Building the project

### ISSUE THREAD

**Issue by urutva** [ARMmbed/mbed-tools#67]
### Description

The project build instructions https://github.com/ARMmbed/mbed-tools/blob/master/docs/howto/mbed-tools-howto.md#build-the-project doesn't mention checking out `feature-cmake` branch of mbed-os. Without this step build fails with 
```
CMake Error at CMakeLists.txt:10 (add_subdirectory):
  The source directory

    /Users/devran01/Documents/devaraj/working/tmp/tmp/mbed-os-example-blinky/mbed-os

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:16 (mbed_configure_app_target):
  Unknown CMake command "mbed_configure_app_target".


-- Configuring incomplete, errors occurred!
```

### Issue request type

- [ ] Enhancement
- [ ] Bug

**Comment by Patater** [comment]
This problem will naturally go away when `feature-cmake` is merged, but remains an issue until then.

**Comment by Patater** [comment]
`feature-cmake` has been merged. We should be all good now. Re-open if not.
