### ISSUE TITLE
No build profile option for `build` sub-command

### ISSUE THREAD

**Issue by hugueskamba** [ARMmbed/mbed-tools#97]
### Description
The ability to specify the build profile when building an application would be nice to have.
For example:
`$ mbedtools build -t <TOOLCHAIN> -m <MBEd_TARGET> -p <BUILD_PROFILE>`

### Issue request type

- [x] Enhancement
- [ ] Bug

**Comment by rwalton-arm** [comment]
You can specify the "profile" using `mbedtools build --build-type <CMAKE_BUILD_TYPE>`
